### ISSUE TITLE
There are some errors in the `Convert Vocabulary` page.

### ISSUE THREAD

**Issue by Lukeehoojet** [UbiquitousLearning/mllm_website#1]
In this [Convert Vocabulary](https://ubiquitouslearning.github.io/mllm_website/customization/convert_vocabulary/) page, the shell script `python vocab.py --input_file=tokenizer.model --output_file=vocab.mllm --type=Unigram` should be `python vocab.py --input_file=tokenizer.json --output_file=vocab.mllm --type=Unigram`.

**Comment by yirongjie** [comment]
fixed
